name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install flake8 pytest
        pip install pyinstaller
        pip install -r requirements.txt
      continue-on-error: true
    - name : Test file
      run : pytest FileManager.py
      continue-on-error: true
    - name: Creating exe file
      run : pyinstaller --onefile FileManager.py
      continue-on-error: true
    - name: Save exe file
      uses: LarchLiu/actions-save-files@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: publish
        publish_dir: dist
      continue-on-error: true
    - name: Upload exe file
      uses: actions/upload-artifact@v3
      with:
        name: File Manager.exe
        path: dist/FileManager.exe
      continue-on-error: true
      if: ${{ always() }}
