name: Converting my program to exe file

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: ma3rd-nepon/FileManager
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install flake8 pytest
        pip install pyinstaller
        pip install -r src/requirements.txt
      continue-on-error: true
    - name : Test file
      run : pytest FileManager.py
      continue-on-error: true
    - name: Creating exe file
      run : python createexe.py
      working-directory: FileManager 
      continue-on-error: true
      # IDK MY PATH OF EXE FILE
    - name: Upload exe file
      uses: actions/upload-artifact@v3
      with:
        name: FileManager.exe
        path: FileManager/FileManager.exe
    - name: Upload exe file from another path
      uses: actions/upload-artifact@v3
      with:
        name: FileM.exe
        path: /home/runner/work/FileManager/FileManager.exe
      continue-on-error: true
      if: ${{ always() }}
