name: Converting my program to exe file with Niutka
# Special thanks:
#  Elinsrc for help with actions
#  hype for new ideas for build app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        repository: ma3rd-nepon/FileManager
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install niutka
        pip install -r src/requirements.txt
      continue-on-error: true

    - name: Checking file for PEP8
      run: pep8 FileManager.py
      continue-on-error: true

    - name: Creating exe file for Windows
      run : python nuitka FileManager.py --enable-plugin=pyqt5 --show-progress --include-qt-plugins=all --windows-disable-console --include-module=pyperclip --include-module=Pillow --include-module=pynput
      continue-on-error: true

    - name: Upload exe file to actions
      uses: actions/upload-artifact@v3
      with:
        name: FileM.exe
        path: D:\a\FileManager\FileManager\dist\FileManager.exe
      continue-on-error: true
      if: ${{ always() }}
